# Generated by Django 3.2 on 2022-03-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.TextField(),
        ),
    ]
